#
# This workflow builds the app and model-check reports, stores them in the `artifacts` branch,
# then deploys the updated `artifacts` directory to GitHub Pages.
#

name: Build

on:
  # Run this workflow on every push to any branch except the special `artifacts` branch
  push:
    branches:
      - '**'
      - '!artifacts'
  # Allow for running this workflow manually from the Actions tab
  workflow_dispatch:

# Set the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  # Allow pushing to the `artifacts` branch
  contents: write
  # Allow deployment to GitHub Pages
  pages: write
  id-token: write

# Allow one concurrent build
concurrency:
  group: 'build'

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Fetch full history for artifact branch operations
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          # XXX: There are issues when this GitHub Actions workflow uses the latest npm version
          # (11.6.2), see relevant issues:
          #   https://github.com/npm/cli/issues/8669
          #   https://github.com/npm/cli/issues/8726
          # For now, use the latest Node 22, which includes an older npm version that works.
          #node-version: lts/*
          node-version: 22
          cache: 'npm'

      - name: Validate branch name
        run: ./scripts/validate-branch-name.js ${{ github.ref_name }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: ./scripts/ci-build.js

      - name: Configure git user
        run: |
          # Configure git so that the commit in the following step is attributed to
          # the current user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Store artifacts in orphan branch
        run: ./scripts/ci-store-artifacts.js ${{ github.ref_name }} ./staged
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      # NOTE: This assumes that the "Store artifacts in orphan branch" step above has
      # already checked out the `artifacts` branch and left it as the current branch
      # (so that the `artifacts` directory is available and up to date)
      - name: Upload GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: './artifacts'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
